[package]
name = "termcast"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
inquire = "0.7.5"
log = "0.4.27"
pretty_env_logger = "0.5.0"
teloxide = { version = "0.15.0", features = ["full"] }
tokio = { version = "1.45.1", features = ["macros", "rt-multi-thread"] }